.DEFAULT_GOAL := help
.PHONY: help install lint type test test-unit test-integration fmt migrate migration up down logs run-api run-worker

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

install: ## Create venv and install dev + test + agents extras (uv)
	uv sync --extra dev --extra test --extra agents

lint: ## Ruff lint
	uv run ruff check src tests

fmt: ## Ruff format + autofix
	uv run ruff format src tests && uv run ruff check --fix src tests

type: ## mypy strict
	uv run mypy src

test-unit: ## Fast unit tests
	uv run pytest tests/unit

test-integration: ## Integration tests (needs Docker for testcontainers)
	uv run pytest tests/integration -m integration

test: ## All tests with coverage
	uv run pytest --cov --cov-report=term-missing

migrate: ## Apply DB migrations
	uv run alembic upgrade head

migration: ## Create a new autogenerated migration: make migration m="add x"
	uv run alembic revision --autogenerate -m "$(m)"

up: ## Start local infra (Postgres, Redis, OTel, Grafana)
	docker compose up -d

down: ## Stop local infra
	docker compose down

logs: ## Tail infra logs
	docker compose logs -f

run-api: ## Run API server
	uv run agentforge api

run-worker: ## Run an execution worker
	uv run agentforge worker
